package com.fleencorp.feen.adapter.google.recaptcha.model.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents the response received from Google reCAPTCHA service.
 * This class encapsulates the response data including success status, hostname, action,
 * score, challenge timestamp, and error codes if any.
 *
 * @author Yusuf Alamu Musa
 * @version 1.0
 */
@Getter
@Setter
@AllArgsConstructor
@ToString
public class ReCaptchaResponse {

  /**
   * Indicates whether the reCAPTCHA verification was successful.
   */
  private boolean success;

  /**
   * The hostname of the site where the reCAPTCHA was solved.
   */
  private String hostname;

  /**
   * The action name provided when the reCAPTCHA was executed.
   */
  private String action;

  /**
   * The score indicating the probability that the request came from a human.
   */
  private float score;

  /**
   * The timestamp of the challenge generated by the reCAPTCHA service.
   */
  @JsonProperty("challenge_ts")
  private LocalDateTime challengeTimeStamp;

  /**
   * List of error codes if the reCAPTCHA verification failed.
   */
  @JsonProperty("error-codes")
  private List<String> errorCodes;
}

