package com.fleencorp.feen.common.constant.base;

import com.fleencorp.base.constant.base.ApiParameter;
import lombok.Getter;

/**
 * Enum representing various types of report messages used in the application.
 *
 * <p>This enum implements the {@link ApiParameter} interface and provides a set of predefined constants
 * that categorize report messages. These types can be used to differentiate the nature of messages
 * generated by the application, aiding in logging, monitoring, and user notifications.</p>
 *
 * @author Yusuf Alamu Musa
 * @version 1.0
 */
@Getter
public enum ReportMessageType implements ApiParameter {

  ERROR("Error"),
  INFO("Info"),
  WARN("Warn"),
  GOOGLE_CALENDAR("Google Calendar"),
  GOOGLE_OAUTH2("Google Oauth2"),
  GOOGLE_CHAT("Google Chat"),
  YOUTUBE("YouTube"),
  PROFILE_VERIFICATION("Profile Verification"),
  GENERAL("General");

  private final String value;

  ReportMessageType(final String value) {
    this.value = value;
  }

  public static ReportMessageType googleOauth2() {
    return GOOGLE_OAUTH2;
  }
}
