--liquibase formatted sql


--changeset alamu:1

--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM role;

INSERT INTO role (title, code) VALUES
  ('Administrator', 'ADMINISTRATOR'),
  ('Pre Authenticated User', 'PRE_AUTHENTICATED_USER'),
  ('Pre Verified User', 'PRE_VERIFIED_USER'),
  ('Refresh Token', 'REFRESH_TOKEN'),
  ('Super Administrator', 'SUPER_ADMINISTRATOR'),
  ('User', 'USER');

--rollback DELETE FROM role WHERE code IN ('SUPER_ADMINISTRATOR', 'ADMINISTRATOR', 'USER', 'PRE_AUTHENTICATED_USER', 'REFRESH_TOKEN', 'PRE_VERIFIED_USER');



--changeset alamu:2

--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM country;

INSERT INTO country (title, code, timezone)
VALUES
  ('Afghanistan', 'AFG', 'Asia/Kabul'),
  ('Albania', 'ALB', 'Europe/Tirane'),
  ('Algeria', 'ALG', 'Africa/Algiers'),
  ('Andorra', 'ARA', 'Europe/Andorra'),
  ('Angola', 'ANG', 'Africa/Luanda'),
  ('Antigua and Barbuda', 'AAB', 'America/Antigua'),
  ('Argentina', 'ARG', 'America/Argentina/Buenos_Aires'),
  ('Armenia', 'ARM', 'Asia/Yerevan'),
  ('Australia', 'AUS', 'Australia/Sydney'),
  ('Austria', 'AST', 'Europe/Vienna'),
  ('Azerbaijan', 'AZR', 'Asia/Baku'),
  ('Bahamas', 'BHS', 'America/Nassau'),
  ('Bahrain', 'BAH', 'Asia/Bahrain'),
  ('Bangladesh', 'BNG', 'Asia/Dhaka'),
  ('Barbados', 'BAR', 'America/Barbados'),
  ('Belarus', 'BEL', 'Europe/Minsk'),
  ('Belgium', 'BLG', 'Europe/Brussels'),
  ('Belize', 'BLZ', 'America/Belize'),
  ('Benin', 'BEN', 'Africa/Porto-Novo'),
  ('Bhutan', 'BHU', 'Asia/Thimphu'),
  ('Bolivia', 'BLV', 'America/La_Paz'),
  ('Bosnia and Herzegovina', 'BHE', 'Europe/Sarajevo'),
  ('Botswana', 'BOT', 'Africa/Gaborone'),
  ('Brazil', 'BRA', 'America/Sao_Paulo'),
  ('Brunei', 'BRU', 'Asia/Brunei'),
  ('Bulgaria', 'BGR', 'Europe/Sofia'),
  ('Burkina Faso', 'BKF', 'Africa/Ouagadougou'),
  ('Burundi', 'BRD', 'Africa/Bujumbura'),
  ('Cote d''Ivoire', 'CDV', 'Africa/Abidjan'),
  ('Cabo Verde', 'CBV', 'Atlantic/Cape_Verde'),
  ('Cambodia', 'CAM', 'Asia/Phnom_Penh'),
  ('Cameroon', 'CER', 'Africa/Douala'),
  ('Canada', 'CAN', 'America/Toronto'),
  ('Central African Republic', 'CAR', 'Africa/Bangui'),
  ('Chad', 'CHA', 'Africa/Ndjamena'),
  ('Chile', 'CHI', 'America/Santiago'),
  ('China', 'CHN', 'Asia/Shanghai'),
  ('Colombia', 'COL', 'America/Bogota'),
  ('Comoros', 'COM', 'Indian/Comoro'),
  ('Congo (Brazzaville)', 'CGB', 'Africa/Brazzaville'),
  ('Congo (Kinshasa)', 'CGK', 'Africa/Kinshasa'),
  ('Costa Rica', 'CRI', 'America/Costa_Rica'),
  ('Croatia', 'CRO', 'Europe/Zagreb'),
  ('Cuba', 'CUB', 'America/Havana'),
  ('Cyprus', 'CYP', 'Asia/Nicosia'),
  ('Czech Republic', 'CZE', 'Europe/Prague'),
  ('Denmark', 'DEN', 'Europe/Copenhagen'),
  ('Djibouti', 'DJI', 'Africa/Djibouti'),
  ('Dominica', 'DOM', 'America/Dominica'),
  ('Dominican Republic', 'DOR', 'America/Santo_Domingo'),
  ('Ecuador', 'ECU', 'America/Guayaquil'),
  ('Egypt', 'EGY', 'Africa/Cairo'),
  ('El Salvador', 'ELS', 'America/El_Salvador'),
  ('Equatorial Guinea', 'EQG', 'Africa/Malabo'),
  ('Eritrea', 'ERT', 'Africa/Asmara'),
  ('Estonia', 'EST', 'Europe/Tallinn'),
  ('Eswatini', 'ESW', 'Africa/Mbabane'),
  ('Ethiopia', 'ETH', 'Africa/Addis_Ababa'),
  ('Fiji', 'FIJ', 'Pacific/Fiji'),
  ('Finland', 'FIN', 'Europe/Helsinki'),
  ('France', 'FRA', 'Europe/Paris'),
  ('Gabon', 'GAB', 'Africa/Libreville'),
  ('Gambia', 'GAM', 'Africa/Banjul'),
  ('Georgia', 'GEO', 'Asia/Tbilisi'),
  ('Germany', 'GER', 'Europe/Berlin'),
  ('Ghana', 'GHA', 'Africa/Accra'),
  ('Greece', 'GRE', 'Europe/Athens'),
  ('Grenada', 'GRD', 'America/Grenada'),
  ('Guatemala', 'GUA', 'America/Guatemala'),
  ('Guinea', 'GUI', 'Africa/Conakry'),
  ('Guinea-Bissau', 'GBS', 'Africa/Bissau'),
  ('Guyana', 'GUY', 'America/Guyana'),
  ('Haiti', 'HAI', 'America/Port-au-Prince'),
  ('Holy See', 'HSE', 'Europe/Vatican'),
  ('Honduras', 'HON', 'America/Tegucigalpa'),
  ('Hungary', 'HUN', 'Europe/Budapest'),
  ('Iceland', 'ICE', 'Atlantic/Reykjavik'),
  ('India', 'IND', 'Asia/Kolkata'),
  ('Indonesia', 'IDN', 'Asia/Jakarta'),
  ('Iran', 'IRN', 'Asia/Tehran'),
  ('Iraq', 'IRQ', 'Asia/Baghdad'),
  ('Ireland', 'IRL', 'Europe/Dublin'),
  ('Israel', 'ISR', 'Asia/Jerusalem'),
  ('Italy', 'ITA', 'Europe/Rome'),
  ('Jamaica', 'JAM', 'America/Jamaica'),
  ('Japan', 'JPN', 'Asia/Tokyo'),
  ('Jordan', 'JOR', 'Asia/Amman'),
  ('Kazakhstan', 'KAZ', 'Asia/Almaty'),
  ('Kenya', 'KEN', 'Africa/Nairobi'),
  ('Kiribati', 'KIR', 'Pacific/Tarawa'),
  ('Korea, North', 'KOR', 'Asia/Pyongyang'),
  ('Korea, South', 'KOS', 'Asia/Seoul'),
  ('Kosovo', 'KV', 'Europe/Belgrade'),
  ('Kuwait', 'KUW', 'Asia/Kuwait'),
  ('Kyrgyzstan', 'KGZ', 'Asia/Bishkek'),
  ('Laos', 'LAO', 'Asia/Vientiane'),
  ('Latvia', 'LAT', 'Europe/Riga'),
  ('Lebanon', 'LEB', 'Asia/Beirut'),
  ('Lesotho', 'LES', 'Africa/Maseru'),
  ('Liberia', 'LBR', 'Africa/Monrovia'),
  ('Libya', 'LBY', 'Africa/Tripoli'),
  ('Liechtenstein', 'LIE', 'Europe/Vaduz'),
  ('Lithuania', 'LTU', 'Europe/Vilnius'),
  ('Luxembourg', 'LUX', 'Europe/Luxembourg'),
  ('Madagascar', 'MAD', 'Indian/Antananarivo'),
  ('Malawi', 'MAW', 'Africa/Blantyre'),
  ('Malaysia', 'MAS', 'Asia/Kuala_Lumpur'),
  ('Maldives', 'MDV', 'Indian/Maldives'),
  ('Mali', 'MLI', 'Africa/Bamako'),
  ('Malta', 'MLT', 'Europe/Malta'),
  ('Marshall Islands', 'MHL', 'Pacific/Majuro'),
  ('Mauritania', 'MTN', 'Africa/Nouakchott'),
  ('Mauritius', 'MUS', 'Indian/Mauritius'),
  ('Mexico', 'MEX', 'America/Mexico_City'),
  ('Micronesia', 'FSM', 'Pacific/Chuuk'),
  ('Moldova', 'MDA', 'Europe/Chisinau'),
  ('Monaco', 'MON', 'Europe/Monaco'),
  ('Mongolia', 'MGL', 'Asia/Ulaanbaatar'),
  ('Montenegro', 'MNE', 'Europe/Podgorica'),
  ('Morocco', 'MAR', 'Africa/Casablanca'),
  ('Mozambique', 'MOZ', 'Africa/Maputo'),
  ('Myanmar', 'MYA', 'Asia/Yangon'),
  ('Namibia', 'NAM', 'Africa/Windhoek'),
  ('Nauru', 'NRU', 'Pacific/Nauru'),
  ('Nepal', 'NEP', 'Asia/Kathmandu'),
  ('Netherlands', 'NED', 'Europe/Amsterdam'),
  ('New Zealand', 'NZL', 'Pacific/Auckland'),
  ('Nicaragua', 'NIC', 'America/Managua'),
  ('Niger', 'NIG', 'Africa/Niamey'),
  ('Nigeria', 'NGA', 'Africa/Lagos'),
  ('North Macedonia', 'MKD', 'Europe/Skopje'),
  ('Norway', 'NOR', 'Europe/Oslo'),
  ('Oman', 'OMA', 'Asia/Muscat'),
  ('Pakistan', 'PAK', 'Asia/Karachi'),
  ('Palau', 'PLW', 'Pacific/Palau'),
  ('Palestinian Territory', 'PLE', 'Asia/Gaza'),
  ('Panama', 'PAN', 'America/Panama'),
  ('Papua New Guinea', 'PNG', 'Pacific/Port_Moresby'),
  ('Paraguay', 'PAR', 'America/Asuncion'),
  ('Peru', 'PER', 'America/Lima'),
  ('Philippines', 'PHI', 'Asia/Manila'),
  ('Poland', 'POL', 'Europe/Warsaw'),
  ('Portugal', 'POR', 'Europe/Lisbon'),
  ('Qatar', 'QAT', 'Asia/Qatar'),
  ('Romania', 'ROM', 'Europe/Bucharest'),
  ('Russia', 'RUS', 'Europe/Moscow'),
  ('Rwanda', 'RWA', 'Africa/Kigali'),
  ('Saint Kitts and Nevis', 'SKN', 'America/St_Kitts'),
  ('Saint Lucia', 'SLU', 'America/St_Lucia'),
  ('Saint Vincent and the Grenadines', 'SVG', 'America/St_Vincent'),
  ('Samoa', 'SAM', 'Pacific/Apia'),
  ('San Marino', 'SMR', 'Europe/San_Marino'),
  ('Sao Tome and Principe', 'STP', 'Africa/Sao_Tome'),
  ('Saudi Arabia', 'SAU', 'Asia/Riyadh'),
  ('Senegal', 'SEN', 'Africa/Dakar'),
  ('Serbia', 'SRB', 'Europe/Belgrade'),
  ('Seychelles', 'SEY', 'Indian/Mahe'),
  ('Sierra Leone', 'SLE', 'Africa/Freetown'),
  ('Singapore', 'SGP', 'Asia/Singapore'),
  ('Slovakia', 'SVK', 'Europe/Bratislava'),
  ('Slovenia', 'SVN', 'Europe/Ljubljana'),
  ('Solomon Islands', 'SLB', 'Pacific/Honiara'),
  ('Somalia', 'SOM', 'Africa/Mogadishu'),
  ('South Africa', 'RSA', 'Africa/Johannesburg'),
  ('South Sudan', 'SSD', 'Africa/Juba'),
  ('Spain', 'ESP', 'Europe/Madrid'),
  ('Sri Lanka', 'SRI', 'Asia/Colombo'),
  ('Sudan', 'SDN', 'Africa/Khartoum'),
  ('Suriname', 'SUR', 'America/Paramaribo'),
  ('Sweden', 'SWE', 'Europe/Stockholm'),
  ('Switzerland', 'SUI', 'Europe/Zurich'),
  ('Syria', 'SYR', 'Asia/Damascus'),
  ('Taiwan', 'TWN', 'Asia/Taipei'),
  ('Tajikistan', 'TJK', 'Asia/Dushanbe'),
  ('Tanzania', 'TAN', 'Africa/Dodoma'),
  ('Thailand', 'THA', 'Asia/Bangkok'),
  ('Timor-Leste', 'TLS', 'Asia/Dili'),
  ('Togo', 'TOG', 'Africa/Lome'),
  ('Tonga', 'TON', 'Pacific/Tongatapu'),
  ('Trinidad and Tobago', 'TRT', 'America/Port_of_Spain'),
  ('Tunisia', 'TUN', 'Africa/Tunis'),
  ('Turkey', 'TUR', 'Europe/Istanbul'),
  ('Turkmenistan', 'TKM', 'Asia/Ashgabat'),
  ('Tuvalu', 'TUV', 'Pacific/Funafuti'),
  ('Uganda', 'UGA', 'Africa/Kampala'),
  ('Ukraine', 'UKR', 'Europe/Kyiv'),
  ('United Arab Emirates', 'UAE', 'Asia/Dubai'),
  ('United Kingdom', 'UK', 'Europe/London'),
  ('United States', 'USA', 'America/New_York'),
  ('Uruguay', 'URU', 'America/Montevideo'),
  ('Uzbekistan', 'UZB', 'Asia/Tashkent'),
  ('Vanuatu', 'VAN', 'Pacific/Efate'),
  ('Venezuela', 'VEN', 'America/Caracas'),
  ('Vietnam', 'VIE', 'Asia/Ho_Chi_Minh'),
  ('Yemen', 'YEM', 'Asia/Aden'),
  ('Zambia', 'ZAM', 'Africa/Lusaka'),
  ('Zimbabwe', 'ZIM', 'Africa/Harare'),
  ('Other','OOO', 'Africa/Lagos');

--rollback DELETE FROM `country`;