--liquibase formatted sql


--changeset alamu:1

--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM role;

INSERT INTO role (title, code) VALUES
  ('Administrator', 'ADMINISTRATOR'),
  ('Pre Authenticated User', 'PRE_AUTHENTICATED_USER'),
  ('Pre Verified User', 'PRE_VERIFIED_USER'),
  ('Refresh Token', 'REFRESH_TOKEN'),
  ('Super Administrator', 'SUPER_ADMINISTRATOR'),
  ('User', 'USER');

--rollback DELETE FROM role WHERE code IN ('SUPER_ADMINISTRATOR', 'ADMINISTRATOR', 'USER', 'PRE_AUTHENTICATED_USER', 'REFRESH_TOKEN', 'PRE_VERIFIED_USER');



--changeset alamu:2

--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM country;

INSERT INTO country (title, code)
VALUES
    ('Afghanistan','AFG'),
    ('Albania','ALB'),
    ('Algeria','ALG'),
    ('Andorra','ARA'),
    ('Angola','ANG'),
    ('Antigua and Barbuda','AAB'),
    ('Argentina','ARG'),
    ('Armenia','ARM'),
    ('Australia','AUS'),
    ('Austria','AST'),
    ('Azerbaijan','AZR'),
    ('Bahamas','BHS'),
    ('Bahrain','BAH'),
    ('Bangladesh','BNG'),
    ('Barbados','BAR'),
    ('Belarus','BEL'),
    ('Belgium','BLG'),
    ('Belize','BLZ'),
    ('Benin','BEN'),
    ('Bhutan','BHU'),
    ('Bolivia','BLV'),
    ('Bosnia and Herzegovina','BHE'),
    ('Botswana','BOT'),
    ('Brazil','BRA'),
    ('Brunei','BRU'),
    ('Bulgaria','BGR'),
    ('Burkina Faso','BKF'),
    ('Burundi','BRD'),
    ('Cote d''Ivoire','CDV'),
    ('Cabo Verde','CBV'),
    ('Cambodia','CAM'),
    ('Cameroon','CER'),
    ('Canada','CAN'),
    ('Central African Republic','CAR'),
    ('Chad','CHA'),
    ('Chile','CHI'),
    ('China','CHN'),
    ('Colombia','COL'),
    ('Comoros','COM'),
    ('Congo (Brazzaville)','CGB'),
    ('Congo (Kinshasa)','CGK'),
    ('Costa Rica','CRI'),
    ('Croatia','CRO'),
    ('Cuba','CUB'),
    ('Cyprus','CYP'),
    ('Czech Republic','CZE'),
    ('Denmark','DEN'),
    ('Djibouti','DJI'),
    ('Dominica','DOM'),
    ('Dominican Republic','DOR'),
    ('Ecuador','ECU'),
    ('Egypt','EGY'),
    ('El Salvador','ELS'),
    ('Equatorial Guinea','EQG'),
    ('Eritrea','ERT'),
    ('Estonia','EST'),
    ('Eswatini','ESW'),
    ('Ethiopia','ETH'),
    ('Fiji','FIJ'),
    ('Finland','FIN'),
    ('France','FRA'),
    ('Gabon','GAB'),
    ('Gambia','GAM'),
    ('Georgia','GEO'),
    ('Germany','GER'),
    ('Ghana','GHA'),
    ('Greece','GRE'),
    ('Grenada','GRD'),
    ('Guatemala','GUA'),
    ('Guinea','GUI'),
    ('Guinea-Bissau','GBS'),
    ('Guyana','GUY'),
    ('Haiti','HAI'),
    ('Holy See','HSE'),
    ('Honduras','HON'),
    ('Hungary','HUN'),
    ('Iceland','ICE'),
    ('India','IND'),
    ('Indonesia','IDN'),
    ('Iran','IRN'),
    ('Iraq','IRQ'),
    ('Ireland','IRL'),
    ('Israel','ISR'),
    ('Italy','ITA'),
    ('Jamaica','JAM'),
    ('Japan','JPN'),
    ('Jordan','JOR'),
    ('Kazakhstan','KAZ'),
    ('Kenya','KEN'),
    ('Kiribati','KIR'),
    ('Korea, North','KOR'),
    ('Korea, South','KOS'),
    ('Kosovo','KV'),
    ('Kuwait','KUW'),
    ('Kyrgyzstan','KGZ'),
    ('Laos','LAO'),
    ('Latvia','LAT'),
    ('Lebanon','LEB'),
    ('Lesotho','LES'),
    ('Liberia','LBR'),
    ('Libya','LBY'),
    ('Liechtenstein','LIE'),
    ('Lithuania','LTU'),
    ('Luxembourg','LUX'),
    ('Madagascar','MAD'),
    ('Malawi','MAW'),
    ('Malaysia','MAS'),
    ('Maldives','MDV'),
    ('Mali','MLI'),
    ('Malta','MLT'),
    ('Marshall Islands','MHL'),
    ('Mauritania','MTN'),
    ('Mauritius','MUS'),
    ('Mexico','MEX'),
    ('Micronesia','FSM'),
    ('Moldova','MDA'),
    ('Monaco','MON'),
    ('Mongolia','MGL'),
    ('Montenegro','MNE'),
    ('Morocco','MAR'),
    ('Mozambique','MOZ'),
    ('Myanmar','MYA'),
    ('Namibia','NAM'),
    ('Nauru','NRU'),
    ('Nepal','NEP'),
    ('Netherlands','NED'),
    ('New Zealand','NZL'),
    ('Nicaragua','NIC'),
    ('Niger','NIG'),
    ('Nigeria','NGA'),
    ('North Macedonia','MKD'),
    ('Norway','NOR'),
    ('Oman','OMA'),
    ('Pakistan','PAK'),
    ('Palau','PLW'),
    ('Palestinian Territory','PLE'),
    ('Panama','PAN'),
    ('Papua New Guinea','PNG'),
    ('Paraguay','PAR'),
    ('Peru','PER'),
    ('Philippines','PHI'),
    ('Poland','POL'),
    ('Portugal','POR'),
    ('Qatar','QAT'),
    ('Romania','ROM'),
    ('Russia','RUS'),
    ('Rwanda','RWA'),
    ('Saint Kitts and Nevis','SKN'),
    ('Saint Lucia','SLU'),
    ('Saint Vincent and the Grenadines','SVG'),
    ('Samoa','SAM'),
    ('San Marino','SMR'),
    ('Sao Tome and Principe','STP'),
    ('Saudi Arabia','SAU'),
    ('Senegal','SEN'),
    ('Serbia','SRB'),
    ('Seychelles','SEY'),
    ('Sierra Leone','SLE'),
    ('Singapore','SGP'),
    ('Slovakia','SVK'),
    ('Slovenia','SVN'),
    ('Solomon Islands','SLB'),
    ('Somalia','SOM'),
    ('South Africa','RSA'),
    ('South Sudan','SSD'),
    ('Spain','ESP'),
    ('Sri Lanka','SRI'),
    ('Sudan','SDN'),
    ('Suriname','SUR'),
    ('Sweden','SWE'),
    ('Switzerland','SUI'),
    ('Syria','SYR'),
    ('Taiwan','TWN'),
    ('Tajikistan','TJK'),
    ('Tanzania','TAN'),
    ('Thailand','THA'),
    ('Timor-Leste','TLS'),
    ('Togo','TOG'),
    ('Tonga','TON'),
    ('Trinidad and Tobago','TRT'),
    ('Tunisia','TUN'),
    ('Turkey','TUR'),
    ('Turkmenistan','TKM'),
    ('Tuvalu','TUV'),
    ('Uganda','UGA'),
    ('Ukraine','UKR'),
    ('United Arab Emirates','UAE'),
    ('United Kingdom','UK'),
    ('United States','USA'),
    ('Uruguay','URU'),
    ('Uzbekistan','UZB'),
    ('Vanuatu','VAN'),
    ('Venezuela','VEN'),
    ('Vietnam','VIE'),
    ('Yemen','YEM'),
    ('Zambia','ZAM'),
    ('Zimbabwe','ZIM'),
    ('Other','OOO');

--rollback DELETE FROM `country`;